# Built from native speakers, with inspiration from
# https://github.com/zacanger/profane-words
# and
# https://github.com/thisandagain/washyourmouthoutwithsoap/blob/develop/data/build.json
# and
# https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words


english_flagged_words = [
    "anal",
    "bareback",
    "bbw",
    "bdsm",
    "blowjob",
    "blowjobs",
    "brazzers",
    "bukkake",
    "camgirl",
    "camwhore",
    "cocksucking",
    "cougar",
    "creampie",
    "cuckold",
    "cum",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cunnilingus",
    "deepthroat",
    "deepthroating",
    "dildo",
    "dildos",
    "dogging",
    "doggystyle",
    "dominatrix",
    "erotic",
    "fellatio",
    "femdom",
    "fingering",
    "fisting",
    "footjob",
    "gangbang",
    "handjob",
    "hentai",
    "horney",
    "horniest",
    "horny",
    "jism",
    "jizz",
    "masterbating",
    "masturbate",
    "masturbating",
    "masturbation",
    "milf",
    "orgies",
    "orgy",
    "pegging",
    "porn",
    "pornhub",
    "porno",
    "pornos",
    "pornstar",
    "pornstars",
    "redtube",
    "rimming",
    "slutty",
    "squirting",
    "strapon",
    "threesome",
    "vibrator",
    "xhamster",
    "xnxx",
    "xvideos",
    "xxx",
    "youporn",
]


flagged_words = {
    "ar": english_flagged_words
    + [
        "إباحي",
        "احتلام",
        "است",
        "استمناء",
        "اغتصاب",
        "أورغازم",
        "إيروتيك",
        "أير",
        "بز",
        "بزاز",
        "بظر",
        "بورن",
        "بيضان",
        "مص",
        "ثدي",
        "جماع",
        "جنس",
        "حلمة",
        "خلاعة",
        "خنثي",
        "خول",
        "دعارة",
        "زب",
        "سحاق",
        "سحاقية",
        "سكس",
        "سيكس",
        "شاذ",
        "شبق",
        "شرج",
        "شرموطة",
        "شهواني",
        "شهوة",
        "طيز",
        "عادة السرية",
        "عاهرة",
        "عرص",
        "فاسقة",
        "فرج",
        "قحبة",
        "قضيب",
        "كس",
        "لحس",
        "لعق",
        "لواط",
        "لوطي",
        "مؤخرة",
        "متناك",
        "متناكة",
        "مومس",
        "مثير",
        "مص",
        "مضاجعة",
        "مفلقسة",
        "مني",
        "مهتاج",
        "نشوة",
        "نكاح",
        "نيك",
    ],
    "bn": english_flagged_words
    + [
        "আঙ্গুলি করা",
        "আচোদা",
        "খানকি",
        "খানকি মাগি",
        "গান্ড মারানো",
        "গুদ মারানি",
        "চুচুক",
        "চোদ",
        "চোদনা",
        "চোদা",
        "চোদা বোন",
        "চোদাচুদি",
        "জারজ",
        "নাঙ্গ",
        "নেংটা",
        "পর্ণহাব",
        "পর্ন",
        "পর্নস্টার",
        "পর্নোগ্রাফি",
        "পোঁদ",
        "পোঁদ মারানি",
        "পোদ মারানি",
        "বাঁড়া",
        "বানচোদ",
        "বেশ্যা",
        "বেশ্যার ছেলে",
        "বোকাচোদা",
        "ভগ",
        "মা চোদা",
        "মাগী",
        "মাদারচোদ",
        "মুখে নিবি",
        "মোরগ",
        "রেন্ডি",
        "শিশ্ন",
        "স্তন",
        "স্তনবৃন্ত",
        "হস্তমৈথুন",
    ],
    "ca": english_flagged_words
    + [
        "cagarro",
        "cagarros",
        "cipote",
        "cipotes",
        "collons",
        "colló",
        "consolador",
        "consoladors",
        "cony",
        "conys",
        "corre's",
        "corre't",
        "corregut",
        "cunillingus",
        "córrer-se",
        "escorreguda",
        "escorregudes",
        "escorregut",
        "escrot",
        "escrots",
        "escórre's",
        "escórre't",
        "escórrer-se",
        "mamada",
        "mamadera",
        "mamaderes",
        "mamades",
        "masturba",
        "masturbacions",
        "masturbació",
        "masturbant",
        "masturbar",
        "masturbar-se",
        "masturbat",
        "masturbats",
        "masturbes",
        "orgasme",
        "orgasmes",
        "ou",
        "ous",
        "palla",
        "palles",
        "pornografia",
        "semen",
        "semens",
        "verga",
        "vergues",
        "xxx",
    ],
    "en": english_flagged_words,
    "es": english_flagged_words
    + [
        "chupar el coño",
        "chupar la concha",
        "chupar la polla",
        "chupar la verga",
        "comer el coño",
        "comer la concha",
        "comer la polla",
        "comer la verga",
        "coprofagía",
        "correrse",
        "cunillingus",
        "fagging",
        "felación",
        "felching",
        "follada",
        "follador de culo",
        "folladores",
        "fudge packer",
        "hacer una paja",
        "hacerse una paja",
        "hore",
        "kock",
        "macizorra",
        "madre folladora",
        "mamada",
        "perro follador",
        "pisser",
        "pornografía",
        "sado",
        "sadomasoquismo",
        "sadomasoquista",
        "sexo anal",
        "skank",
        "smegma",
        "x clasificado",
    ],
    "eu": english_flagged_words + [],
    "fr": english_flagged_words
    + [
        "baiseurs",
        "baiseur",
        "baiseuse",
        "baiseuses",
        "branlette",
        "branlettes",
        "branleuse",
        "branleuses",
        "cunillingus",
        "cunilingus",
        "enculée",
        "enculées",
        "enculation",
        "enculations",
        "enculement",
        "enculements",
        "fellation",
        "fellations",
        "porno",
        "pornos",
        "pornographie",
        "pornographique",
        "pornographiques",
        "salope",
        "salopes",
        "suceuse",
        "suceuses",
        "xxx",
    ],
    "hi": english_flagged_words
    + [
        "अंडकोश की थैली",
        "एक्स रेटेड",
        "ओगाज़्म",
        "कामोद्दीपक चित्र",
        "कालीन का चूरा",
        "कून",
        "कॉक",
        "गेंद का थैला",
        "चाकलेट का रंग",
        "चूची",
        "चूतड़",
        "झटका बंद",
        "ठगना पैकर",
        "डिल्डो",
        "नितंब",
        "पिछाड़ी",
        "पीड़न कामुक",
        "पॉर्न",
        "फटना",
        "फूहड़",
        "बट",
        "बहुत मदहोश",
        "बेल अंत",
        "भगवान-शापित",
        "भगशेफ",
        "माँ कमीने",
        "मुखमैथुन",
        "मुर्गा चूसने वाला",
        "रक्तरंजित",
        "लेबिया",
        "वहशी",
        "वहशीता",
        "वैंग",
        "शिश्नमल",
        "संभोग सुख",
        "सह शॉट",
        "सींग का बना हुआ",
        "होर",
        "घपा घप",
        "चुदाई",
        "चुदक्कड़",
    ],
    "id": english_flagged_words
    + [
        "bokep",
        "coli",
        "colmek",
        "grepe",
        "horni",
        "janda",
        "jembut",
        "jilat memek",
        "jilmek",
        "kontol",
        "masturbasi",
        "memek",
        "ngentot",
        "ngewe",
        "peju",
        "pepek",
        "pornografi",
        "sange",
        "sepong",
        "tusbol",
    ],
    "pt": english_flagged_words
    + [
        "balalao",
        "bate uma",
        "beijo grego",
        "boceta",
        "boquete",
        "buceta",
        "caralho",
        "chochota",
        "coito",
        "cona",
        "consolo",
        "corno",
        "cu",
        "dar a bunda",
        "dar o rabo",
        "dildo",
        "dildos",
        "esporrar",
        "estrovenga",
        "felação",
        "filho da puta",
        "filhos da puta",
        "gozada",
        "jeba",
        "perereca",
        "pica",
        "piru",
        "porno",
        "pornografia",
        "pornô",
        "porra",
        "prostituta",
        "pube",
        "punheta",
        "punheteiro",
        "putaria",
        "queca",
        "sexo",
        "siririca",
        "tesão",
        "trepada",
        "verga",
        "vibrador",
        "xana",
        "xochota",
        "xoxota",
    ],
    "ur": english_flagged_words
    + [
        "انگلی کرنا",
        "ایکس ریٹیڈ",
        "بلو جاب",
        "بٹ",
        "جھٹکا بند",
        "دلڈو",
        "رنڈی",
        "سلٹ",
        "سکلیرا",
        "سیڈسٹ",
        "سیکس بم",
        "شہوانی",
        "شہوت انگیز",
        "فحش نگاری",
        "لن",
        "لنڈ",
        "لنڈ چوسنے والا",
        "لوڑہ",
        "ماں کمینے",
        "مشت زنی",
        "ممے",
        "مٹھ",
        "مٹھی",
        "ویشیا",
        "پورن",
        "پھدی",
        "پیگنگ",
        "چدائ",
        "چدک",
        "چوت",
        "چودنا",
        "چوچی",
        "کسبی",
        "کسنگ",
        "گانڈ",
        "گدا",
        "ہینڈ جاب",
    ],
    "vi": english_flagged_words
    + [
        "cặc",
        "lồn",
        "địt",
        "buồi",
        "đụ",
        "nứng",
        "phò",
        "bú lol",
        "bú lon",
        "bú cac",
        "bú cak",
        "bú cax",
        "bú buoi",
        "bú mút",
        "húp lol",
        "húp lon",
        "húp sò",
        "nung lol",
        "nung lon",
        "nug lon",
        "nung cac",
        "nung buoi",
        "thèm dit",
        "thèm lon",
        "thèm lol",
        "thèm buoi",
        "thèm dit",
        "thèm chich",
        "thèm chịch",
        "thèm cax",
        "thèm cak",
        "móc lol",
        "móc lon",
        "buscu",
        "lol non",
        "bướm non",
        "vú to",
        "vú bự",
        "lon to",
        "phim sex",
        "phim xex",
        "phim xxx",
    ],
    "zh": english_flagged_words
    + [
        "三级片",
        "乳交",
        "卖B",
        "卖比",
        "卖淫",
        "口交",
        "姣西",
        "打炮",
        "打飞机",
        "抽插",
        "招妓",
        "插你",
        "插死你",
        "淫水",
        "肉壁",
        "肉棍子",
        "肉缝",
        "肏",
        "肛交",
    ],
    "ja": english_flagged_words
    + [
        "sm女王",
        "アジアのかわいい女の子",
        "アスホール",
        "アナリングス",
        "アナル",
        "いたずら",
        "イラマチオ",
        "エクスタシー",
        "エスコート",
        "エッチ",
        "エロティズム",
        "エロティック",
        "オーガズム",
        "オカマ",
        "おしっこ",
        "おしり",
        "オシリ",
        "おしりのあな",
        "おっぱい",
        "オッパイ",
        "オナニー",
        "オマンコ",
        "おもらし",
        "お尻",
        "カーマスートラ",
        "カント",
        "クリトリス",
        "グループ・セックス",
        "グロ",
        "クンニリングス",
        "ゲイ・セックス",
        "ゲイボーイ",
        "ゴールデンシャワー",
        "コカイン",
        "ゴックン",
        "サディズム",
        "しばり",
        "スウィンガー",
        "スカートの中",
        "スカトロ",
        "ストラップオン",
        "ストリップ劇場",
        "スラット",
        "スリット",
        "セクシーな",
        "セクシーな",
        "セックス",
        "ソドミー",
        "ちんこ",
        "ディープ・スロート",
        "ディック",
        "ディルド",
        "デートレイプ",
        "デブ",
        "テレフォンセックス",
        "ドッグスタイル",
        "トップレス",
        "なめ",
        "ニガー",
        "ヌード",
        "ネオ・ナチ",
        "ハードコア",
        "パイパン",
        "バイブレーター",
        "バック・スタイル",
        "パンティー",
        "ビッチ",
        "ファック",
        "ファンタジー",
        "フィスト",
        "フェティッシュ",
        "フェラチオ",
        "ふたなり",
        "ぶっかけ",
        "フック",
        "プリンス",
        "プレイボーイ",
        "ベアバック",
        "ペニス",
        "ペニスバンド",
        "ボーイズラブ",
        "ボールギャグ",
        "ぽっちゃり",
        "ホモ",
        "ポルノ",
        "ポルノグラフィー",
        "ボンテージ",
        "マザー・ファッカー",
        "マスターベーション",
        "まんこ",
        "やおい",
        "やりまん",
        "ラティーナ",
        "ラバー",
        "ランジェリー",
        "レイプ",
        "レズビアン",
        "ローター",
        "ロリータ",
        "淫乱",
        "陰毛",
        "革抑制",
        "騎上位",
        "巨根",
        "巨乳",
        "強姦犯",
        "玉なめ",
        "玉舐め",
        "緊縛",
        "近親相姦",
        "嫌い",
        "後背位",
        "合意の性交",
        "拷問",
        "殺し方",
        "殺人事件",
        "殺人方法",
        "支配",
        "児童性虐待",
        "自己愛性",
        "射精",
        "手コキ",
        "獣姦",
        "女の子",
        "女王様",
        "女子高生",
        "女装",
        "新しいポルノ",
        "人妻",
        "性交",
        "正常位",
        "生殖器",
        "精液",
        "挿入",
        "足フェチ",
        "足を広げる",
        "大陰唇",
        "脱衣",
        "茶色のシャワー",
        "中出し",
        "潮吹き女",
        "潮吹き男性",
        "直腸",
        "剃毛",
        "貞操帯",
        "奴隷",
        "二穴",
        "乳首",
        "尿道プレイ",
        "覗き",
        "売春婦",
        "縛り",
        "噴出",
        "糞",
        "糞尿愛好症",
        "糞便",
        "平手打ち",
        "変態",
        "勃起する",
        "夢精",
        "毛深い",
        "誘惑",
        "幼児性愛者",
        "裸の女性",
        "乱交",
        "両刀",
        "輪姦",
        "卍",
        "宦官",
        "肛門",
        "膣",
    ],
    "de": english_flagged_words
    + [
        "analritter",
        "arsch",
        "arschficker",
        "arschlecker",
        "arschloch",
        "bimbo",
        "bratze",
        "bumsen",
        "bonze",
        "dödel",
        "fick",
        "ficken",
        "flittchen",
        "fotze",
        "fratze",
        "hackfresse",
        "hure",
        "hurensohn",
        "ische",
        "kackbratze",
        "kacke",
        "kacken",
        "kackwurst",
        "kampflesbe",
        "kanake",
        "kimme",
        "lümmel",
        "MILF",
        "möpse",
        "morgenlatte",
        "möse",
        "mufti",
        "muschi",
        "nackt",
        "neger",
        "nigger",
        "nippel",
        "nutte",
        "onanieren",
        "orgasmus",
        "penis",
        "pimmel",
        "pimpern",
        "pinkeln",
        "pissen",
        "pisser",
        "popel",
        "poppen",
        "porno",
        "reudig",
        "rosette",
        "schabracke",
        "schlampe",
        "scheiße",
        "scheisser",
        "schiesser",
        "schnackeln",
        "schwanzlutscher",
        "schwuchtel",
        "tittchen",
        "titten",
        "vögeln",
        "vollpfosten",
        "wichse",
        "wichsen",
        "wichser",
    ],
    "ru": english_flagged_words
    + [
        "bychara",
        "byk",
        "chernozhopyi",
        "dolboy'eb",
        "ebalnik",
        "ebalo",
        "ebalom",
        "gol",
        "mudack",
        "opizdenet",
        "osto'eblo",
        "ostokhuitel'no",
        "ot'ebis",
        "otmudohat",
        "otpizdit",
        "otsosi",
        "padlo",
        "pedik",
        "perdet",
        "petuh",
        "pidar",
        "pizda",
        "pizdato",
        "pizdatyi",
        "piz'det",
        "pizdetc",
        "pizdoi",
        "pizd'uk",
        "piz`dyulina",
        "podi",
        "poeben",
        "po'imat'",
        "po'iti",
        "po",
        "poluchit",
        "pososi",
        "prissat",
        "proebat",
        "promudobl'adsksya",
        "propezdoloch",
        "prosrat",
        "raspeezdeyi",
        "raspizdatyi",
        "raz'yebuy",
        "raz'yoba",
        "s'ebat'sya",
        "shalava",
        "styervo",
        "sukin",
        "svodit",
        "svoloch",
        "trakhat'sya",
        "trimandoblydskiy",
        "ubl'yudok",
        "uboy",
        "u'ebitsche",
        "vafl'a",
        "vafli",
        "v",
        "vyperdysh",
        "vzdrochennyi",
        "yeb",
        "za'ebat",
        "zaebis",
        "zalupa",
        "zalupat",
        "zasranetc",
        "zassat",
        "zlo'ebuchy",
        "бздёнок",
        "блядки",
        "блядовать",
        "блядство",
        "блядь",
        "бугор",
        "во",
        "встать",
        "выёбываться",
        "гандон",
        "говно",
        "говнюк",
        "голый",
        "дать",
        "дерьмо",
        "дрочить",
        "другой",
        "ёбарь",
        "ебать",
        "ебать-копать",
        "ебло",
        "ебнуть",
        "ёб",
        "жопа",
        "жополиз",
        "играть",
        "измудохать",
        "каждый",
        "какая",
        "как",
        "курите",
        "лысого",
        "малофья",
        "манда",
        "мандавошка",
        "мент",
        "муда",
        "мудило",
        "мудозвон",
        "наебать",
        "наебениться",
        "наебнуться",
        "на",
        "на",
        "на",
        "на",
        "нахуячиться",
        "невебенный",
        "не",
        "ни",
        "ни",
        "обнаженный",
        "обоссаться",
        "один",
        "опесдол",
        "офигеть",
        "охуеть",
        "охуительно",
        "половое",
        "секс",
        "сиськи",
        "спиздить",
        "срать",
        "ссать",
        "траxать",
        "ты",
        "фига",
        "хапать",
        "хер",
        "хер",
        "хохол",
        "хрен",
        "хуёво",
        "хуёвый",
        "хуем",
        "хуеплет",
        "хуило",
        "хуиней",
        "хуиня",
        "хуй",
        "хуйнуть",
        "хуй",
    ],
}
